apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipcomponent-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: ipcomponent
  template:
    metadata:
      labels:
        app: ipcomponent
    spec:
      containers:
      - name: ipcomponent
        image: yash5090/ipcomponent:latest
        ports:
        - containerPort: 5000
