apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipcomponent-deployment
spec:
  replicas: 2 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: ipcomponent
  template:
    metadata:
      labels:
        app: ipcomponent
    spec:
      containers:
        - name: ipcomponent
          image: yash5090/ipcomponent:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
